### ISSUE TITLE
[BUG] Not able to select table. Only see the query tab and no table details. 

### ISSUE THREAD

**Issue by robertc11** [cweijan/vscode-mysql#366] opened 2021-11-22 16:41 UTC
Hi, 

We are not able to select our tables starting this morning.   We are running React on CentOS 7 system.  See attached image. 

- OS INFO : CentOS 7

![Select Table Issue](https://user-images.githubusercontent.com/4958651/142900530-a672c458-4279-422a-98c6-cc79a4e40d99.PNG)

**Comment by cweijan** [comment] 2021-11-23 01:30
Try to close the page and reopen it. The new version optimizes the cache usage, but it seems that there is a problem with the current logic.

**Comment by JaakkoRoponen** [comment] 2021-11-23 14:15
I have the same problem. Can't figure out a solution. Even uninstalling and reinstalling the extension does not help.

**Comment by alexandernst** [comment] 2021-11-23 14:31
I'm also experiencing this issue. This started happening after updating to 4.2.1

**Comment by JaakkoRoponen** [comment] 2021-11-23 14:40
Yes, rolling back to 4.2.0 fixes the issue

**Comment by wangpengcheng** [comment] 2021-11-24 07:07
Rolling back to 4.2.0 fixes this issue

**Comment by cweijan** [comment] 2021-11-24 07:11
Have you tried to closing the result view in version 4.2.1 then reopen? the new version will be released in a few days, I think he can avoid this problem.

**Comment by JaakkoRoponen** [comment] 2021-11-24 07:14
Yes. Also tried reinstall, but didn't help either.

**Comment by cweijan** [comment] 2021-11-24 07:16
@JaakkoRoponen  Hi, try restart vscode, then query table and give feedback, it will be very helpful to me.

**Comment by JaakkoRoponen** [comment] 2021-11-24 07:21
I just get an empty query tab without any content (as shown in the initial post). Nothing I do changes that (except rolling back to previous version).

**Comment by cweijan** [comment] 2021-11-24 09:24
Do you use remote vscode? It is currently known that remote can cause this problem.

**Comment by alexandernst** [comment] 2021-11-24 09:49
I do use remote vscode (and I'm having this issue)

**Comment by cweijan** [comment] 2021-11-24 09:57
If it is caused by remote, it will be fixed in the next version.

**Comment by cweijan** [comment] 2021-11-24 14:20
Try version 4.2.3.

**Comment by robertc11** [comment] 2021-11-24 15:22
The latest version is working for me. I was using remote vs code. Thank you so much for quick response and help.

**Closed as completed** 2021-11-27 02:42 UTC
Labels: bug
