### ISSUE TITLE
[BUG] run sql on view error [Illegal mix of collations (utf8mb4_bin,NONE) and (utf8mb4_unicode_ci,COERCIBLE) for operation 'like']

### ISSUE THREAD

**Issue by jiangbing321** [cweijan/vscode-mysql#747] opened 2023-01-13 05:41 UTC
- OS:
- Mac
- Database Type:
- Mysql
- Extension Version:
- v6.1.1

I run the sql "select count(*) from view_course_grades WHERE grade_ids LIKE '%,6,%';"  on a view.  It shows an error:

SQL:  select count(*) from view_course_grades WHERE grade_ids LIKE '%,6,%';

Illegal mix of collations (utf8mb4_bin,NONE) and (utf8mb4_unicode_ci,COERCIBLE) for operation 'like'

But It is ok when I run the sql on mysql command client.  I don't what's the reason. 
Could you help me, thanks.

**Comment by cweijan** [comment] 2023-01-13 05:50
This seems to be caused by collation, I will try to fix it.

**Comment by cweijan** [comment] 2023-01-13 06:14
Hi, this error should be a bug of the version of MySQL you are using, I can't handle it.

Please try to upgrade your MySQL version, or change the collation of the grade_ids field in the original table of the view from utf8mb4_bin to utf8mb4_unicode_ci.

**Comment by cweijan** [comment] 2024-06-08 11:12
Closing this question as it is not client-side related.

**Closed as completed by cweijan** 2024-06-08 11:12 UTC
Labels: bug
